### ISSUE TITLE
目前的英文词库覆盖范围似乎比较小

### ISSUE THREAD

**Issue by GRDpengyuyan** [bs10081/Rime-Cx330#2]
目前发现部分常见单词无法在双拼状态下无法联想输入（不知道形容得是否确切）：比如，onedrive，youtube，microsoft，our，based（动词的过去式似乎没有包含，但是好像其他输入法也不包含）等，暂时发现这么几个没有包含在英文词库中。
柴妹辛苦了！

**Comment by bs10081** [comment]
嗷給，我之後處理一下這個問題

**Comment by bs10081** [comment]
目前這個功能在我的main裡面已經有了一定的支持了哦，隨後我會發佈新的版本
![image](https://user-images.githubusercontent.com/38148679/106409851-77966780-647c-11eb-86b2-4c6645efbf7d.png)
![image](https://user-images.githubusercontent.com/38148679/106409864-82e99300-647c-11eb-80dd-b33add9d4eae.png)
![image](https://user-images.githubusercontent.com/38148679/106409878-8b41ce00-647c-11eb-8e74-1b8ac6142a47.png)

**Comment by BlindingDark** [comment]
欢迎使用 https://github.com/BlindingDark/rime-easy-en 😎

**Comment by bs10081** [comment]
> 欢迎使用 https://github.com/BlindingDark/rime-easy-en 😎

哇，這個真的是太棒了🥰，給你點個小星星✨，我試試看將你的方案融到我的裡面😁

**Comment by GRDpengyuyan** [comment]
> 欢迎使用 https://github.com/BlindingDark/rime-easy-en 😎

感谢您的分享！！！柴妹似乎已经把您的资源加入到了词库，但是没有加入到方案里面

**Comment by GRDpengyuyan** [comment]
> > 欢迎使用 https://github.com/BlindingDark/rime-easy-en 😎
> 
> 哇，这个真的是太棒了🥰，给你点个小星星✨，我试试看将你的方案融到我的里面😁

柴妹，辛苦了！！！

**Comment by GRDpengyuyan** [comment]
柴妹，我现在又发现一个问题：拼音输入状态下的英文联想，似乎会降低输入效率，通过词库联想出的英文始终会处于候选词第一个，这样可能会造成冲突，又或者说是降低输入效率，举一个例子，小鹤双拼状态下输入“理论”这两个字，双拼要打出“l-i-l-y”,此时，lily这个人名就出现了，而且始终出现在候选词第一个，但是很明显理论才是绝大多数时候想要上屏的词汇。
我记得国内的输入法，往往都会强制部分英文联想词汇固定出现在第二个候选位置（不知道有没有记错）。不知道我提了那么多问题，柴妹会不会抓狂，哈哈哈。

**Comment by GRDpengyuyan** [comment]
![Snipaste_2021-02-02_16-09-53](https://user-images.githubusercontent.com/78254666/106570796-52cfec00-6571-11eb-9470-26fa777317bb.png)
这个是手心输入法输入理论的时候，出现的候选词

**Comment by bs10081** [comment]
> 柴妹，我现在又发现一个问题：拼音输入状态下的英文联想，似乎会降低输入效率，通过词库联想出的英文始终会处于候选词第一个，这样可能会造成冲突，又或者说是降低输入效率，举一个例子，小鹤双拼状态下输入“理论”这两个字，双拼要打出“l-i-l-y”,此时，lily这个人名就出现了，而且始终出现在候选词第一个，但是很明显理论才是绝大多数时候想要上屏的词汇。
> 我记得国内的输入法，往往都会强制部分英文联想词汇固定出现在第二个候选位置（不知道有没有记错）。不知道我提了那么多问题，柴妹会不会抓狂，哈哈哈。

這個問題我去看看能不能通過修改優先級來解決，不過可能會需要一段時間才能解決

**Comment by GRDpengyuyan** [comment]
柴妹，感觉个人来优化输入法的打字逻辑真的挺费劲的啊。
另外还有一点，不知道rime有没有智能词频功能，微软IME似乎就没有，比如，微软IME输入一个用户造的词汇，这个词可能比较生僻，这个生僻词还有其他常见的同音词，下次输入同音的其他常见词时候，这个生僻词会出现在第一个候选，而有智能词频控制的输入法可能就会动态调节。RIME似乎也有类似微软IME的情况，似乎也没有智能词频。

**Comment by GRDpengyuyan** [comment]
> > 柴妹，我现在又发现一个问题：拼音输入状态下的英文联想，似乎会降低输入效率，通过词库联想出的英文始终会处于候选词第一个，这样可能会造成冲突，又或者说是降低输入效率，举一个例子，小鹤双拼状态下输入“理论”这两个字，双拼要打出“l-i-l-y”,此时，lily这个人名就出现了，而且始终出现在候选词第一个，但是很明显理论才是绝大多数时候想要上屏的词汇。
> > 我记得国内的输入法，往往都会强制部分英文联想词汇固定出现在第二个候选位置（不知道有没有记错）。不知道我提了那么多问题，柴妹会不会抓狂，哈哈哈。
> 
> 这个问题我去看看能不能通过修改优先级来解决，不过可能会需要一段时间才能解决

谢谢柴妹！！辛苦辛苦！！！

**Comment by bs10081** [comment]
> 柴妹，感觉个人来优化输入法的打字逻辑真的挺费劲的啊。
> 另外还有一点，不知道rime有没有智能词频功能，微软IME似乎就没有，比如，微软IME输入一个用户造的词汇，这个词可能比较生僻，这个生僻词还有其他常见的同音词，下次输入同音的其他常见词时候，这个生僻词会出现在第一个候选，而有智能词频控制的输入法可能就会动态调节。RIME似乎也有类似微软IME的情况，似乎也没有智能词频。

這個問題還要研究一下，畢竟我現在對於Rime的底層運作方式還不是很瞭解

**Comment by BlindingDark** [comment]
@GRDpengyuyan 

> 英文始终会处于候选词第一个

调整 `easy_en/initial_quality` 的值，数字越大，越靠前，如
```yaml
easy_en/initial_quality: -1
```
效果：

![image](https://user-images.githubusercontent.com/13600799/106587182-44d79680-6584-11eb-8ffd-7c63520dba8f.png)

[相关说明](https://github.com/BlindingDark/rime-easy-en#%E6%B7%B7%E8%BE%93%E6%97%B6%E8%8B%B1%E6%96%87%E5%8D%95%E8%AF%8D%E6%8E%92%E7%9A%84%E5%A4%AA%E9%9D%A0%E5%90%8E)


> 智能词频功能

`translator/enable_user_dict` 设置为 true 即可开启调频。

**Comment by bs10081** [comment]
> @GRDpengyuyan 
> 
> 
> 
> > 英文始终会处于候选词第一个
> 
> 
> 
> 调整 `easy_en/initial_quality` 的值，数字越大，越靠前，如
> 
> ```yaml
> 
> easy_en/initial_quality: -1
> 
> ```
> 
> 效果：
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/13600799/106587182-44d79680-6584-11eb-8ffd-7c63520dba8f.png)
> 
> 
> 
> [相关说明](https://github.com/BlindingDark/rime-easy-en#%E6%B7%B7%E8%BE%93%E6%97%B6%E8%8B%B1%E6%96%87%E5%8D%95%E8%AF%8D%E6%8E%92%E7%9A%84%E5%A4%AA%E9%9D%A0%E5%90%8E)
> 
> 
> 
> -----
> 
> 
> 
> > 智能词频功能
> 
> 
> 
> `translator/enable_user_dict` 设置为 true 即可开启调频。

哇這個好，感謝🙏

**Comment by GRDpengyuyan** [comment]
> @GRDpengyuyan
> 
> > 英文始终会处于候选词第一个
> 
> 调整 `easy_en/initial_quality` 的值，数字越大，越靠前，如
> 
> ```yaml
> easy_en/initial_quality: -1
> ```
> 
> 效果：
> 
> ![image](https://user-images.githubusercontent.com/13600799/106587182-44d79680-6584-11eb-8ffd-7c63520dba8f.png)
> 
> [相关说明](https://github.com/BlindingDark/rime-easy-en#%E6%B7%B7%E8%BE%93%E6%97%B6%E8%8B%B1%E6%96%87%E5%8D%95%E8%AF%8D%E6%8E%92%E7%9A%84%E5%A4%AA%E9%9D%A0%E5%90%8E)
> 
> > 智能词频功能
> 
> `translator/enable_user_dict` 设置为 true 即可开启调频。

感谢大佬，我已经按照教程调整了双拼里面英文的候选词位置了。
![Snipaste_2021-02-02_23-04-35](https://user-images.githubusercontent.com/78254666/106619048-246f0280-65ab-11eb-98c5-23d603fc309e.png)

**Comment by GRDpengyuyan** [comment]
> `translator/enable_user_dict` 设置为 true 即可开启调频。

“translator/enable_user_dict 设置为 true 即可开启调频。”
但是，这个我没找到相应的位置。我回头咨询一下柴妹大佬。

**Comment by bs10081** [comment]
> > `translator/enable_user_dict` 设置为 true 即可开启调频。
> 
> “translator/enable_user_dict 设置为 true 即可开启调频。”
> 但是，这个我没找到相应的位置。我回头咨询一下柴妹大佬。

沒找到就自己寫一行啊😂，這個功能我已經在測試了，之後釋出的版本就會搭載了
