### ISSUE TITLE
启用 easy_en 功能后，用户自定义码表失效

### ISSUE THREAD

**Issue by inoton** [bs10081/Rime-Cx330#6]
# 问题描述
您好，

确认当前版本中，一旦启用了 easy_en 插件后，自定义码表功能将失效。

如何验证？
将 `wubi_pinyin.custom.yaml` 配置文件中的最后一节 `#加载 easy_en 依赖` 整体注释掉并重新部署后，custom_phrase.txt 中的码表变为可用。

# 系统环境：
Fedora33  5.11.5-50.fc33.x86_64  GNU/Linux
GNOME Shell 3.38.3 
XORG and wayland

# 软件版本：
ibus-1.5.23-2.fc33.x86_64
ibus-rime-1.4.0-6.fc33.x86_64
输入法为五笔拼音

🐄 感谢提供如此优秀的配置方案，可用性已经远超微软开发的输入法。

**Comment by bs10081** [comment]
感謝您的誇獎，
由於我不會使用五筆，所以五筆的功能僅僅維持在理論能使用的階段，之後我會專門排查這個問題，希望能早日修正這個問題。

您使用我的輸入法配置是我的榮幸，謝謝您😁

**Comment by bs10081** [comment]
此問題已修復，效果如下👇🏻
![CleanShot 2021-03-24 at 12 46 30](https://user-images.githubusercontent.com/38148679/112256673-25fda280-8c9f-11eb-8371-15fc70bcef33.gif)
